FakeShop.App/Models/ErrorViewModel.cs
namespace FakeShop.App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FakeShop.App/Models/Order.cs
namespace FakeShop.App.Models
{
    public class Order
    {
        public int ProductId { get; set; }
        public short Quantity { get; set; }
    }
}

FakeShop.App/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace FakeShop.App.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "{0:N2}", ApplyFormatInEditMode = true)]
        public double Price { get; set; }
        public string Category { get; set; }
    }
}

FakeShop.App/Controllers/FakeStoreController.cs
using FakeShop.App.Integrations;
using FakeShop.App.Models;
using Microsoft.AspNetCore.Mvc;

namespace FakeShop.App.Controllers
{
    public class FakeStoreController : Controller
    {
        private readonly IFakeShopApiClient _apiClient;

        public FakeStoreController(IFakeShopApiClient apiClient)
        {
            _apiClient = apiClient ?? 
                throw new ArgumentNullException(nameof(apiClient));
        }

        public async Task<IActionResult> Index()
        {
            var products = await _apiClient.GetProducts();
            return View(products);
        }

        public async Task<IActionResult> Order(int id) 
        {
            var orderId = await _apiClient.PlaceOrder(
                new Order 
                { 
                    ProductId = id, 
                    Quantity = 1 
                });

            return View("OrderConfirmation", orderId);
        }
    }
}

FakeShop.App/Controllers/HomeController.cs
using FakeShop.App.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FakeShop.App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FakeShop.App/Views/FakeStore/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "Fake Store";
}

<div class="text-center">
    <h1>You wish we had the mountaineering stuff you are looking for, nah ;)</h1>
    <h3>Magically no-one-size fits all!!</h3>
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th class="d-flex justify-content-center">@Html.DisplayNameFor(model => model.Description)</th>
                <th>@Html.DisplayNameFor(model => model.Price)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="/images/@(item.Id).jpg" alt="@item.Name" height="100" width="100" />
                        <br />
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        € @Html.DisplayFor(modelItem => item.Price)
                        <br />
                        <a asp-action="Order" asp-route-id="@item.Id">Buy Now</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

FakeShop.App/Views/FakeStore/OrderConfirmation.cshtml
@model System.Guid;

@{
    ViewData["Title"] = "Order Confirmation";
}

<h1>Thanks for your order!</h1>
<h4>Your Order Id is: @Model</h4>

FakeShop.App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron jumbotron-fluid crf-hero d-flex">
    <div class="container d-flex flex-column justify-content-center align-items-sm-stretch align-items-md-center">
        <h1 class="col-sm-12">GET A GRIP</h1>
        <h2>70% OFF</h2>
        <h3 class="lead">THROUGHOUT THE SILLY SEASON</h3>
    </div>
</div>

FakeShop.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FakeShop.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FakeShop.App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FakeShop.App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FakeStore" asp-action="Index">FakeStore</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FakeShop.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>